version: '2'
services:

    food-data-inference:
        image: plataformacf
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
            - ./plataformacf:/var/www/
        ports:
            - "5000:80"