version: '2'
services:

    plataformacf:
        image: plataformacf
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
            - ./plataformacf:/var/www/
        ports:
            - "5000:80"
        entrypoint: ["sh", "/var/www/entrypoint.sh"]