version: '2'
services:

    plataformacf:
        image: gcr.io/ordinal-stone-180317/plataformacf:v0.0.1
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
            - ./plataformacf:/var/www/
        ports:
            - "5000:80"
        entrypoint: ["sh", "/var/www/entrypoint.sh"]
