<h4>¿Quién es Crowdfunding México?</h4>
<p>Es una iniciativa del Fondo Multilateral de Inversiones (FOMIN) del Banco Interamericano de Desarrollo (BID) ejecutado por la Universidad Anáhuac a través del Centro IDEARSE con la participación de Nacional Financiera, el Instituto Nacional del Emprendedor, la Oficina de Estrategia Digital de la Presidencia de la República, la Comisión Nacional Bancaria y de Valores y la Asociación de Plataformas de Fondeo Colectivo, para impulsar proyectos vía crowdfunding o de financiamiento/fondeo colectivo, ecosistema que está en una fase inicial en México, y que es considerado un mercado alternativo de fondeo para proyectos innovadores a través de plataformas digitales.</p>

<h4>¿Cómo funciona Crowdfunding México?</h4>
<p>El proyecto reforzará el ecosistema de financiamiento colectivo mediante la consolidación de la Asociación de Plataformas de Fondeo Colectivo (AFICO), liderada por las principales plataformas de financiamiento colectivo de México. Ésta recibirá asistencia técnica para colaborar con agentes clave a fin de facilitar el diálogo para estudiar los parámetros de un marco prudencial propicio para la aceleración del desarrollo del ecosistema. Ese apoyo se basará en prácticas óptimas reconocidas en materia de financiamiento colectivo, según la experiencia de mercados desarrollados, y velará por que se considere adecuadamente el contexto local. Los conocimientos generados en la puesta a prueba de este nuevo modelo de intervención serán extraordinariamente valiosos para llenar los vacíos de conocimiento actuales y diseñar iniciativas de financiamiento colectivo similares en otros países. </p>
 
<h4>Aceleración del ecosistema de financiamiento colectivo</h4>
<p>El proyecto pondrá a prueba un modelo de intervención colaborativa enfocado en acelerar el desarrollo de un ecosistema de financiamiento colectivo sostenible en México. En consonancia con las recomendaciones del informe sobre financiamiento colectivo en México, el modelo cubrirá la brecha entre la demanda de financiamiento de los empresarios y las MIPYME, el entendimiento del mercado y las fuentes de financiamiento. Al fortalecer las capacidades de las plataformas de financiamiento colectivo existentes y crear un entorno propicio para el surgimiento de nuevas plataformas, permitirá que los empresarios y las MIPYME las aprovechen mejor y tengan acceso a una multitud de nuevas oportunidades de negocios.</p>

<h4>Asistencia Técnica</h4>
<p>El proyecto línea, brindará a empresas y emprendedores locales (en especial, empresas sociales y negocios liderados por mujeres y jóvenes) asistencia técnica que mejorará su capacidad para utilizar tecnologías digitales y gestionar operaciones comerciales. Pondrá en práctica una estrategia de divulgación incluyente focalizada en los beneficiarios por medio de asociaciones de pequeñas empresas, redes afiliadas de contrapartes del proyecto (por ejemplo, la Red de Apoyo al Emprendedor del INADEM), y estudiantes universitarios. Además, con miras a maximizar su alcance y garantizar iguales oportunidades de formación, el proyecto creará herramientas de capacitación a las que se podrá acceder en línea.</p>

<h4>Capacitación</h4>
<p>El proyecto también ofrecerá capacitación a los microinversionistas potenciales, a efecto de mejorar su capacidad para identificar y evaluar las oportunidades de financiamiento colectivo basado en donaciones, recompensas y préstamos, y los riesgos pertinentes. Es posible que también se imparta capacitación avanzada a inversionistas acreditados, con miras a informarles acerca de las plataformas de financiamiento colectivo basado en acciones, las oportunidades actuales y las limitaciones y riesgos. En todas las actividades de capacitación se pondrá énfasis especial en las consideraciones pertinentes para apoyar con financiamiento colectivo financiero y no financiero a las empresas sociales y los negocios liderados por mujeres o jóvenes, o propiedad de mujeres o jóvenes. Con objeto de maximizar el acceso, también se pondrá a disposición de los microinversionistas material en línea.</p>

<h4>Beneficios del Crowdfunding México</h4>
<p>El proyecto prevé que se operen diversos cambios en el comportamiento de los empresarios y las MIPYME. Las actividades educativas y promocionales, aunadas a la elaboración y diseminación de materiales didácticos pertinentes, fomentarán el uso de las plataformas de financiamiento colectivo entre los empresarios y los microinversionistas.</p>

<h4>Sistema de Monitoreo</h4>
<p>El proyecto prevé que se operen diversos cambios en el comportamiento de los empresarios y las MIPYME. Las actividades educativas y promocionales, aunadas a la elaboración y diseminación de materiales didácticos pertinentes, fomentarán el uso de las plataformas de financiamiento colectivo entre los empresarios y los microinversionistas.</p>




